// Permission codes for easy reference in your application
const PERMISSIONS = {
  // Authentication
  AUTH: {
    LOGIN: 'AUTH_LOGIN',
    SIGNUP: 'AUTH_SIGNUP',
    LOGOUT: 'AUTH_LOGOUT',
    FORGOT_PASSWORD: 'AUTH_FORGOT_PASSWORD',
    VERIFY_OTP: 'AUTH_VERIFY_OTP',
    RESET_PASSWORD: 'AUTH_RESET_PASSWORD',
    CHANGE_PASSWORD: 'AUTH_CHANGE_PASSWORD',
    REFRESH_TOKEN: 'AUTH_REFRESH_TOKEN',
    GET_ME: 'AUTH_GET_ME',
    VERIFY_EMAIL: 'AUTH_VERIFY_EMAIL'
  },

  // User Management
  USER: {
    VIEW_ALL: 'USER_VIEW_ALL',
    VIEW_BY_ID: 'USER_VIEW_BY_ID',
    CREATE: 'USER_CREATE',
    UPDATE: 'USER_UPDATE',
    DELETE: 'USER_DELETE',
    VIEW_ACTIVE: 'USER_VIEW_ACTIVE',
    TOGGLE_STATUS: 'USER_TOGGLE_STATUS',
    VERIFY: 'USER_VERIFY',
    CHANGE_PASSWORD: 'USER_CHANGE_PASSWORD'
  },

  // Role Management
  ROLE: {
    VIEW_ALL: 'ROLE_VIEW_ALL',
    VIEW_BY_ID: 'ROLE_VIEW_BY_ID',
    CREATE: 'ROLE_CREATE',
    UPDATE: 'ROLE_UPDATE',
    DELETE: 'ROLE_DELETE',
    VIEW_ACTIVE: 'ROLE_VIEW_ACTIVE',
    SEARCH: 'ROLE_SEARCH',
    ACTIVATE: 'ROLE_ACTIVATE',
    DEACTIVATE: 'ROLE_DEACTIVATE'
  },

  // Permission Management
  PERMISSION: {
    VIEW_ALL: 'PERMISSION_VIEW_ALL',
    VIEW_BY_ID: 'PERMISSION_VIEW_BY_ID',
    CREATE: 'PERMISSION_CREATE',
    UPDATE: 'PERMISSION_UPDATE',
    DELETE: 'PERMISSION_DELETE',
    VIEW_ACTIVE: 'PERMISSION_VIEW_ACTIVE',
    VIEW_BY_CODE: 'PERMISSION_VIEW_BY_CODE',
    ACTIVATE: 'PERMISSION_ACTIVATE',
    DEACTIVATE: 'PERMISSION_DEACTIVATE',
    TOGGLE_STATUS: 'PERMISSION_TOGGLE_STATUS'
  },

  // Battalion Management
  BATTALION: {
    VIEW_ALL: 'BATTALION_VIEW_ALL',
    VIEW_BY_ID: 'BATTALION_VIEW_BY_ID',
    CREATE: 'BATTALION_CREATE',
    UPDATE: 'BATTALION_UPDATE',
    DELETE: 'BATTALION_DELETE',
    VIEW_BY_RANGE: 'BATTALION_VIEW_BY_RANGE',
    VIEW_BY_DISTRICT: 'BATTALION_VIEW_BY_DISTRICT',
    TOGGLE_STATUS: 'BATTALION_TOGGLE_STATUS'
  },

  // Module Management
  MODULE: {
    VIEW_ALL: 'MODULE_VIEW_ALL',
    VIEW_BY_ID: 'MODULE_VIEW_BY_ID',
    CREATE: 'MODULE_CREATE',
    UPDATE: 'MODULE_UPDATE',
    DELETE: 'MODULE_DELETE',
    VIEW_ACTIVE: 'MODULE_VIEW_ACTIVE',
    VIEW_STATS: 'MODULE_VIEW_STATS',
    SEARCH: 'MODULE_SEARCH',
    VIEW_TOPICS: 'MODULE_VIEW_TOPICS',
    VIEW_PERMISSIONS: 'MODULE_VIEW_PERMISSIONS',
    UPDATE_ORDER: 'MODULE_UPDATE_ORDER',
    CLONE: 'MODULE_CLONE',
    ACTIVATE: 'MODULE_ACTIVATE',
    DEACTIVATE: 'MODULE_DEACTIVATE',
    TOGGLE_STATUS: 'MODULE_TOGGLE_STATUS'
  },

  // Topic Management
  TOPIC: {
    VIEW_ALL: 'TOPIC_VIEW_ALL',
    VIEW_BY_ID: 'TOPIC_VIEW_BY_ID',
    CREATE: 'TOPIC_CREATE',
    UPDATE: 'TOPIC_UPDATE',
    DELETE: 'TOPIC_DELETE',
    VIEW_ACTIVE: 'TOPIC_VIEW_ACTIVE',
    VIEW_BY_MODULE: 'TOPIC_VIEW_BY_MODULE',
    SEARCH: 'TOPIC_SEARCH'
  },

  // Sub-Topic Management
  SUBTOPIC: {
    VIEW_ALL: 'SUBTOPIC_VIEW_ALL',
    VIEW_BY_ID: 'SUBTOPIC_VIEW_BY_ID',
    CREATE: 'SUBTOPIC_CREATE',
    UPDATE: 'SUBTOPIC_UPDATE',
    DELETE: 'SUBTOPIC_DELETE',
    VIEW_ACTIVE: 'SUBTOPIC_VIEW_ACTIVE',
    VIEW_BY_TOPIC: 'SUBTOPIC_VIEW_BY_TOPIC'
  },

  // Question Management
  QUESTION: {
    VIEW_ALL: 'QUESTION_VIEW_ALL',
    VIEW_BY_ID: 'QUESTION_VIEW_BY_ID',
    CREATE: 'QUESTION_CREATE',
    UPDATE: 'QUESTION_UPDATE',
    DELETE: 'QUESTION_DELETE',
    VIEW_ACTIVE: 'QUESTION_VIEW_ACTIVE',
    VIEW_BY_TOPIC: 'QUESTION_VIEW_BY_TOPIC',
    VIEW_BY_SUBTOPIC: 'QUESTION_VIEW_BY_SUBTOPIC',
    SEARCH: 'QUESTION_SEARCH',
    BULK_CREATE: 'QUESTION_BULK_CREATE',
    ACTIVATE: 'QUESTION_ACTIVATE',
    DEACTIVATE: 'QUESTION_DEACTIVATE'
  },

  // Performance Statistics
  PERFORMANCE: {
    VIEW_FORM: 'PERFORMANCE_VIEW_FORM',
    VIEW_FORM_MODULE_TOPIC: 'PERFORMANCE_VIEW_FORM_MODULE_TOPIC',
    SAVE_STATISTICS: 'PERFORMANCE_SAVE_STATISTICS',
    VIEW_ALL: 'PERFORMANCE_VIEW_ALL',
    VIEW_BY_ID: 'PERFORMANCE_VIEW_BY_ID',
    CREATE: 'PERFORMANCE_CREATE',
    UPDATE: 'PERFORMANCE_UPDATE',
    DELETE: 'PERFORMANCE_DELETE',
    BULK_SAVE: 'PERFORMANCE_BULK_SAVE',
    VIEW_BY_USER: 'PERFORMANCE_VIEW_BY_USER',
    VIEW_SUMMARY: 'PERFORMANCE_VIEW_SUMMARY',
    SEND_OTP: 'PERFORMANCE_SEND_OTP',
    VERIFY_OTP: 'PERFORMANCE_VERIFY_OTP',
    MAKE_ACTIVE: 'PERFORMANCE_MAKE_ACTIVE'
  },

  // Menu Management
  MENU: {
    VIEW_ALL: 'MENU_VIEW_ALL',
    VIEW_BY_ID: 'MENU_VIEW_BY_ID',
    CREATE: 'MENU_CREATE',
    UPDATE: 'MENU_UPDATE',
    DELETE: 'MENU_DELETE',
    VIEW_ACTIVE: 'MENU_VIEW_ACTIVE',
    ACTIVATE: 'MENU_ACTIVATE',
    DEACTIVATE: 'MENU_DEACTIVATE'
  },

  // Sub-Menu Management
  SUBMENU: {
    VIEW_ALL: 'SUBMENU_VIEW_ALL',
    VIEW_BY_ID: 'SUBMENU_VIEW_BY_ID',
    CREATE: 'SUBMENU_CREATE',
    UPDATE: 'SUBMENU_UPDATE',
    DELETE: 'SUBMENU_DELETE',
    VIEW_ACTIVE: 'SUBMENU_VIEW_ACTIVE',
    VIEW_BY_MENU: 'SUBMENU_VIEW_BY_MENU',
    VIEW_BY_PARENT: 'SUBMENU_VIEW_BY_PARENT',
    ACTIVATE: 'SUBMENU_ACTIVATE',
    DEACTIVATE: 'SUBMENU_DEACTIVATE'
  },

  // Communication Management
  COMMUNICATION: {
    VIEW_ALL: 'COMMUNICATION_VIEW_ALL',
    VIEW_BY_ID: 'COMMUNICATION_VIEW_BY_ID',
    CREATE: 'COMMUNICATION_CREATE',
    UPDATE: 'COMMUNICATION_UPDATE',
    DELETE: 'COMMUNICATION_DELETE',
    VIEW_USER: 'COMMUNICATION_VIEW_USER',
    SEND_MESSAGE: 'COMMUNICATION_SEND_MESSAGE'
  },

  // Geography Management
  STATE: {
    VIEW_ALL: 'STATE_VIEW_ALL',
    VIEW_BY_ID: 'STATE_VIEW_BY_ID',
    CREATE: 'STATE_CREATE',
    UPDATE: 'STATE_UPDATE',
    DELETE: 'STATE_DELETE',
    VIEW_ACTIVE: 'STATE_VIEW_ACTIVE'
  },

  DISTRICT: {
    VIEW_ALL: 'DISTRICT_VIEW_ALL',
    VIEW_BY_ID: 'DISTRICT_VIEW_BY_ID',
    CREATE: 'DISTRICT_CREATE',
    UPDATE: 'DISTRICT_UPDATE',
    DELETE: 'DISTRICT_DELETE',
    VIEW_ACTIVE: 'DISTRICT_VIEW_ACTIVE'
  },

  RANGE: {
    VIEW_ALL: 'RANGE_VIEW_ALL',
    VIEW_BY_ID: 'RANGE_VIEW_BY_ID',
    CREATE: 'RANGE_CREATE',
    UPDATE: 'RANGE_UPDATE',
    DELETE: 'RANGE_DELETE',
    VIEW_ACTIVE: 'RANGE_VIEW_ACTIVE'
  },

  // Reports
  REPORT: {
    VIEW_ALL: 'REPORT_VIEW_ALL',
    GENERATE: 'REPORT_GENERATE',
    EXPORT: 'REPORT_EXPORT'
  },

  // CID Management
  CID: {
    CATEGORY_VIEW_ALL: 'CID_CATEGORY_VIEW_ALL',
    DATA_VIEW_ALL: 'CID_DATA_VIEW_ALL',
    DATA_CREATE: 'CID_DATA_CREATE',
    DATA_UPDATE: 'CID_DATA_UPDATE'
  },

  // File Management
  FILE: {
    UPLOAD: 'FILE_UPLOAD',
    DOWNLOAD: 'FILE_DOWNLOAD',
    DELETE: 'FILE_DELETE'
  },

  // Admin Functions
  ADMIN: {
    DASHBOARD: 'ADMIN_DASHBOARD',
    SYSTEM_STATS: 'ADMIN_SYSTEM_STATS',
    HEALTH_CHECK: 'ADMIN_HEALTH_CHECK'
  },

  // API Health
  API: {
    HEALTH: 'API_HEALTH',
    DOCS: 'API_DOCS'
  }
};

module.exports = PERMISSIONS;